Components
marcelomaidden/book_store_cms pull request #2
Opened 2021-02-17 21:16 UTC by marcelomaidden

## Components
At this pull request, I add Redux functionalities and connect the App to the Redux store:
- Changes project folder structure adding components, containers, actions and, reducer folders
- Adds Book, BooksForm, BookList components
- Adds CREATE_BOOK, REMOVE_BOOK actions
- Uses combineReducers to create the root reducer
- Creates the store with the default state for the application
- Adds Bootstrap and basic CSS for form and table

2021-02-17 23:41 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @marcelomaidden, great job on this project :+1: The PR is professional with a title and a short description :slightly_smiling_face: The README file is professional :fireworks: Commit messages well written :100: However, I have let a comment in some of the files we need to fix. Kindly address them :+1: 

Once these are fixed, kindly submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-17 23:41 UTC, addod19 commented on src/containers/BookList.js
> +
- Our BookList Component should connect to Redux store and fetches books from the state
-  It also uses `mapStateToProps` to fetch books from the `store`
- It displays books list in HTML table using `Book` component

2021-02-17 23:41 UTC, addod19 commented on src/components/BooksForm.js
> +const BooksForm = () => (
- Our BookForm component must be in the src/containers directory

2021-02-17 23:41 UTC, addod19 commented on src/containers/App.js
> +const App = ({ books }) => (
Our App component must be in the src/components directory! Let us fix it :smile:

2021-02-18 03:55 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-18 11:56 UTC, merged